const inlineScriptHashes = [
	'Ub0faIfh9pRr7IqFUxeHz+y5lk/hc3CR+8kSvXeKkpA=',
	'Buluswg2h40UWBJJGuNJDJveceDUyunuXhvURs8pijQ=',
	'qPT3eRiQqoNWC0JjPW4BGbhCZZcZLivixGFU2nkXyoM=',
	'ajG7m1i7XCkHQ80goM3zz+oFVWmFfJF/SRQdm08L3Xc=',
	'ynhqWi+XxpNyq9tBP3bdEO5ykQwRYjypCI//RJgjMFo=',
	'mFFWrmsJRs1Zpfn637hUDtaHT+LTzil6MITl3lQwlg8=',
	'SOKmBQhl9eb6BVQzekcMTdL39abNgFg68YCP4+ojh0Q=',
	'PIFvBvNd/F4cbriYY4g7LZGAdVyavQx1/qCoymrsh2g=',
	'xGG43co0rerqFPObHXYwvIZsjVSN8415HHAeZTER+fc=',
];

// Astro emits small module bundles inline and deliberately inlines component CSS.
// The post-build check keeps these script hashes synchronized with generated HTML.
const contentSecurityPolicy = [
	"default-src 'self'",
	"base-uri 'self'",
	"object-src 'none'",
	"frame-ancestors 'none'",
	"form-action 'self'",
	`script-src 'self' ${inlineScriptHashes.map((hash) => `'sha256-${hash}'`).join(' ')}`,
	"script-src-attr 'none'",
	"style-src 'self' 'unsafe-inline'",
	"img-src 'self' data:",
	"font-src 'self'",
	"connect-src 'self'",
	"manifest-src 'self'",
].join('; ');

export const siteConfig = {
	name: 'ADAM SALICKI',
	siteName: 'Adam Salicki Portfolio',
	authorName: 'Adam Salicki',
	language: 'en',
	locale: 'en_US',
	siteUrl: 'https://adamsalicki.pages.dev',
	seoTitle: 'Adam Salicki | Developer & Creative Portfolio',
	seoDescription: 'Explore Adam Salicki’s portfolio of web development projects, creative experiments, and ways to get in touch for collaborations and opportunities.',
	socialTitle: 'Adam Salicki — Portfolio',
	socialDescription: 'Front-end developer expanding into cybersecurity.',
	socialImage: {
		src: '/social-preview.png',
		type: 'image/png',
		width: 1_200,
		height: 630,
		alt: 'Adam Salicki portfolio',
	},
	seoKeywords: [
		'Adam Salicki',
		'cybersecurity portfolio',
		'computer science graduate',
		'entry-level cybersecurity',
		'React developer',
		'systems administration',
		'Wazuh',
		'Proxmox homelab',
	],
	robots: 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
	notFoundRobots: 'noindex, follow',
	themeColor: '#08665f',
	favicon: {
		src: '/favicon.svg',
		type: 'image/svg+xml',
		width: 512,
		height: 512,
	},
	appleTouchIcon: {
		src: '/apple-touch-icon.png',
		type: 'image/png',
		width: 180,
		height: 180,
	},
	additionalIcons: [
		{ src: '/favicon.png', type: 'image/png', width: 512, height: 512 },
		{ src: '/favicon-32x32.png', type: 'image/png', width: 32, height: 32 },
		{ src: '/favicon-16x16.png', type: 'image/png', width: 16, height: 16 },
	],
	faviconIco: {
		src: '/favicon.ico',
		type: 'image/x-icon',
		sizes: [
			{ width: 16, height: 16 },
			{ width: 32, height: 32 },
			{ width: 48, height: 48 },
		],
	},
	webManifest: {
		path: '/site.webmanifest',
		shortName: 'Portfolio',
		startUrl: '/',
		scope: '/',
		display: 'standalone',
		icons: [
			{
				src: '/android-chrome-192x192.png',
				type: 'image/png',
				width: 192,
				height: 192,
				purpose: 'any',
			},
			{
				src: '/android-chrome-512x512.png',
				type: 'image/png',
				width: 512,
				height: 512,
				purpose: 'any',
			},
		],
	},
	responseHeaders: {
		'Content-Security-Policy': contentSecurityPolicy,
		'Strict-Transport-Security': 'max-age=63072000; includeSubDomains',
		'X-Content-Type-Options': 'nosniff',
		'Referrer-Policy': 'strict-origin-when-cross-origin',
		'Permissions-Policy': 'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()',
		'X-Frame-Options': 'DENY',
	},
	contactEmail: 'contact.asalicki@protonmail.com',
	githubUrl: 'https://github.com/adamsiem4',
	linkedinUrl: 'https://linkedin.com/in/adam-salicki-054a84295',
	privacyNotice: {
		title: 'Privacy & data notice',
		summary: 'This static portfolio does not use advertising trackers, analytics beacons, tracking cookies, or contact forms.',
		preference: 'Your selected color theme is stored locally in your browser and is used only to remember that preference.',
		hosting: 'The site is hosted on Cloudflare Pages. Cloudflare may process limited technical data, including IP addresses and request metadata, to deliver, secure, and operate its network.',
		contact: 'If you choose to email me, I use the information you provide only to respond to your message.',
		providerUrl: 'https://www.cloudflare.com/privacypolicy/',
	},
};
