export const siteConfig = {
	name: 'ADAM SALICKI',
	authorName: 'Adam Salicki',
	siteUrl: 'https://adamsalicki.pages.dev',
	seoTitle: 'Adam Salicki | Developer & Creative Portfolio',
	seoDescription: 'Explore Adam Salicki’s portfolio of web development projects, creative experiments, and ways to get in touch for collaborations and opportunities.',
	seoKeywords: [
		'Adam Salicki',
		'cybersecurity portfolio',
		'computer science graduate',
		'entry-level cybersecurity',
		'React developer',
		'systems administration',
		'Wazuh',
		'Proxmox homelab',
	],
	robots: 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
	themeColor: '#08665f',
	contactEmail: 'contact.asalicki@protonmail.com',
	githubUrl: 'https://github.com/adamsiem4',
	linkedinUrl: 'https://linkedin.com/in/adam-salicki-054a84295',
};
